# Change these first
owner: danielcaldwell # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Daniel Caldwell https://www.danielcaldwell.com
    url: https://www.danielcaldwell.com
    slug: daniel-caldwell
  - name: San Info Tech Online https://saninfotechonline.com
    url: https://saninfotechonline.com
    slug: san-info-tech-online
  - name: Blog https://danielcaldwell.bearblog.dev/blog/
    url: https://danielcaldwell.bearblog.dev/blog/
    slug: daniel-caldwell-bearblog
  - name: Finding Sunsets https://findingsunsets.com/
    url: https://findingsunsets.com/
    slug: finding-sunsets
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime status for my sites."
  introMessage: "Big thanks to [**Upptime**](https://github.com/upptime/upptime) for creating this super simple way to check uptime!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
